<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//div[contains(@name,'_jointAccountDtls:listCustRelationshipDtls')]</description>
   <name>ListCustRelationship_list</name>
   <tag></tag>
   <elementGuidId>0666b0d0-33c8-4162-8b4a-60f7b3786b40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@name,'_jointAccountDtls:listCustRelationshipDtls')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
