<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Capture</name>
   <tag></tag>
   <elementGuidId>763c83b8-2ab8-414e-b0a2-b72c3245c9f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'Button_12')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uitype</name>
      <type>Main</type>
      <value>Button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Button_12116a33a7e6dd1hBL%7036</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Capture</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-props</name>
      <type>Main</type>
      <value>readOnly:false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Capture</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>require([&quot;uxp/events&quot;], function(events){events.eventsToInvoke({&quot;callService&quot;:[&quot;{\&quot;srcFormId\&quot;:\&quot;116a33a7e6dd1hBL%7036\&quot;,\&quot;requestMapping\&quot;:{\&quot;03Gender\&quot;:\&quot;[\\\&quot;createPersonalPartyRq:createPersonPartyInput:partyPersonDtl:gender116a33a7e6dd1hBL%7036\\\&quot;]\&quot;,\&quot;03LastName\&quot;:\&quot;[\\\&quot;namedtl:lastName116a33a7e6dd1hBL%7036\\\&quot;]\&quot;,\&quot;03Title\&quot;:\&quot;[\\\&quot;namedtl:title116a33a7e6dd1hBL%7036\\\&quot;]\&quot;,\&quot;03MotherName\&quot;:\&quot;[\\\&quot;createPersonalPartyRq:createPersonPartyInput:partyPersonDtl:mothersMaidenName116a33a7e6dd1hBL%7036\\\&quot;]\&quot;,\&quot;03PartyID\&quot;:\&quot;[\\\&quot;createPersonalPartyRq:createPersonPartyInput:partyBasicDtls:partyId116a33a7e6dd1hBL%7036\\\&quot;]\&quot;,\&quot;03FirstName\&quot;:\&quot;[\\\&quot;namedtl:firstName116a33a7e6dd1hBL%7036\\\&quot;]\&quot;,\&quot;03MiddleName\&quot;:\&quot;[\\\&quot;namedtl:middleNames116a33a7e6dd1hBL%7036\\\&quot;]\&quot;,\&quot;03uploadBiometricRq:uploadBiometricInput:biometricDtl:partyID\&quot;:\&quot;[\\\&quot;createPersonalPartyRq:createPersonPartyInput:partyBasicDtls:partyId116a33a7e6dd1hBL%7036\\\&quot;]\&quot;,\&quot;03FatherName\&quot;:\&quot;[\\\&quot;createPersonalPartyRq:createPersonPartyInput:partyPersonDtl:fathersName116a33a7e6dd1hBL%7036\\\&quot;]\&quot;,\&quot;03PartyType\&quot;:\&quot;[\\\&quot;createPersonalPartyRq:createPersonPartyInput:partyBasicDtls:partyType116a33a7e6dd1hBL%7036\\\&quot;]\&quot;,\&quot;04DOB\&quot;:\&quot;[\\\&quot;createPersonalPartyRq:createPersonPartyInput:partyPersonDtl:dateOfBirth116a33a7e6dd1hBL%7036\\\&quot;]\&quot;},\&quot;serviceDisplayName\&quot;:\&quot;PT_PFN_BMSUploadBiometric_PRC\&quot;,\&quot;controlId\&quot;:\&quot;Button_12116a33a7e6dd1hBL%7036\&quot;,\&quot;serviceName\&quot;:\&quot;PT_PFN_BMSUploadBiometric_PRC\&quot;,\&quot;widgetType\&quot;:\&quot;DIALOG\&quot;}&quot;]});});</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Button_12116a33a7e6dd1hBL%7036&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Button_12116a33a7e6dd1hBL%7036']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='116a33a7e6dd1hBL%7036']/table/tbody/tr[20]/td[4]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signature/Photograph/Fingerprint'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biometrics'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COUNTRYOFOPERATION'])[1]/preceding::input[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTENSIONDETAILS_HOSTEXTENSION'])[1]/preceding::input[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td[4]/input</value>
   </webElementXpaths>
</WebElementEntity>
