<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LineofBusiness_List</name>
   <tag></tag>
   <elementGuidId>1f37ca51-855b-4426-84ec-5180f7230bed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[text()='${description}']/preceding-sibling::td/child::div[contains(@id,'PartyLineOfBusinessDetail')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
