import com.kms.katalon.core.util.KeywordUtil as KeywordUtil
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI

import commons.AbtractTest as AbtractTest
import pageObjects.PartyOnboarding as PartyOnboarding
import report.ExcelFiles as ExcelFiles

PartyOnboarding partyOnboardingPersonal = new PartyOnboarding()
AbtractTest abtractTest = new AbtractTest()
ExcelFiles excelFiles = new ExcelFiles()
KeywordUtil log = new KeywordUtil()
String results = ""

WebUI.delay(3)
log.logInfo("--- Open Party Onboarding in Menu Search ---")
partyOnboardingPersonal.inputPartyOnboardingMenuSearch()

log.logInfo("--- Input Local Global ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputLocalGlobal(s05_localglobal)
log.logInfo("--- Input Party Type ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputPartyType(s05_partytype)
log.logInfo("--- Input Party Sub Type ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputPartySubType(s05_partysubtype)
log.logInfo("--- Input Party Category ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputPartyCategory(s05_partycategory)
log.logInfo("--- Check Line of Business ---")
//partyOnboardingPersonal.clickLineofBusiness(s05_lineofbusiness, findTestObject('PartyOnboarding/PartyOnboarding/div_Core Banking'))
log.logInfo("--- Click Next to Party Check List  ---")
//WebUI.delay(n)
partyOnboardingPersonal.clickNextbutton()
WebUI.delay(1)
//WebUI.delay(n)
log.logInfo("--- Click Next to Party Pre-Existence Check  ---")
partyOnboardingPersonal.clickNextbutton()
WebUI.delay(1)
log.logInfo("--- Input data on Party Pre-Existence Check  ---")
partyOnboardingPersonal.inputPreExistenceCheck(s08_firstname, s08_dateofbirth, s08_nationalldType, s08_nationalldNo, s08_lastname, s08_strState, s08_district01, s08_district02, s08_district03, s08_strType, s08_strregstrationNo)
log.logInfo("--- Click Next button ---")
//WebUI.delay(n)
partyOnboardingPersonal.clickNextbutton()
log.logInfo("--- Key in data all required fields on Personal Party - PartyId ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputPartyId()
log.logInfo("--- Key in data all required fields on Personal Party - Input Nation Identifer Type ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputNationalIdentifierType(s09_nationIdentifierType)
log.logInfo("--- Key in data all required fields on Personal Party - Input Nation Identifer ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputNationalIdentifier(s09_nationIdentifier)
log.logInfo("--- Key in data all required fields on Personal Party - Input Title ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputTitle(s09_title)
log.logInfo("--- Key in data all required fields on Personal Party - Input Employment Status ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputEmploymentStatus(s09_employmentStatus)
log.logInfo("--- Key in data all required fields on Personal Party - Input Gender ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputGender(s09_gender)
log.logInfo("--- Key in data all required fields on Personal Party - Input Civil Status ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputCivilStatus(s09_civilStatus)
log.logInfo("--- Key in data all required fields on Personal Party - Input Mother's Maiden Name ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputMotherMaidenName(s09_motherMaidenName)
//WebUI.delay(n)
log.logInfo("--- Key in data all required fields on Personal Party - Input Short Name ---")
partyOnboardingPersonal.inputShortName(s09_shortName)
log.logInfo("---Key in data all required fields on Personal Party - Input Grandfather's Name ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputGrandfatherName(s09_grandfatherName)
log.logInfo("---Key in data all required fields on Personal Party - Input Nationality ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputNationality(s09_nationality)
log.logInfo("--- Key in data all required fields on Personal Party - Input Resident Status ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputResidentStatus(s09_residentStatus)
log.logInfo("--- Key in data all required fields on Personal Party - Input Tax ID Number ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputTaxIDNumber(s09_taxIDNumber)
log.logInfo("--- Key in data all required fields on Personal Party - Input Religion ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputReligion(s09_religion)
log.logInfo("--- Key in data all required fields on Personal Party - Click Next button ---")
//WebUI.delay(n)
partyOnboardingPersonal.clickNextbutton()
log.logInfo("--- Key in data all required fields on Personal Party - Click Process on Warning box ---")
//WebUI.delay(n)
partyOnboardingPersonal.clickProcessInWarningBox()

//WebUI.delay(n)
log.logInfo("--- Input required fields for Party Address - Input Address Type, User of Communication and Valid From---")
partyOnboardingPersonal.inputRDataForAddressParty(s10_addressType, s10_userForCommunication, s10_validFrom)
log.logInfo("--- Input required fields for Party Address - click Next button---")
//WebUI.delay(n)
partyOnboardingPersonal.clickNextbutton()
log.logInfo("--- Input data for Party Contacts ---")
//WebUI.delay(n)
partyOnboardingPersonal.inputDataForPartyContacts( s11_contactMethod, s11_contactTypeLocation ,s11_contactCountryCode , s11_contactAreaCode , s11_contactNumber , s11_contactEmail, s11_confirmEmail , s11_validFrom )
log.logInfo("--- Input data for Party Contacts - click Next ---")
//WebUI.delay(n)
partyOnboardingPersonal.clickNextbutton()
log.logInfo("--- Input Party Required Documents - Input information for document---")
//WebUI.delay(n)
partyOnboardingPersonal.inputDataForPartyRequiredDocuments( s12_documentCategory, s12_kycExpired,s12_documentType, s12_validFrom, s12_validTo, s12_referenceNumber, s12_issuingAuthority, s12_issuingCountry, s12_documentVerified, s12_image, s12_documentCollectionStatus)
log.logInfo("--- Input Party Required Documents - Click Next button---")
//WebUI.delay(n)
partyOnboardingPersonal.clickNextbutton()
log.logInfo("--- Input Party Required Documents - Record PartyID ---")
//WebUI.delay(n)
//partyOnboardingPersonal.recordPartyId()
log.logInfo("--- Ask For Approve - Click Next button ---")
partyOnboardingPersonal.clickNextbutton()
log.logInfo("--- Ask For Approve - Click Ask For Approval button ---")
//WebUI.delay(n)
partyOnboardingPersonal.clickAskForApprovalbutton()


