<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Image ID_Attach</name>
   <tag></tag>
   <elementGuidId>416edc09-0b7a-4f36-b1be-c0716ce238d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'Attach_4')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uitype</name>
      <type>Main</type>
      <value>Button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Attach_4116a34bb033224cR%8822</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Attach</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-props</name>
      <type>Main</type>
      <value>readOnly:false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Attach</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>require([&quot;uxp/events&quot;], function(events){events.eventsToInvoke({&quot;callService&quot;:[&quot;{\&quot;srcFormId\&quot;:\&quot;116a34bb033224cR%8822\&quot;,\&quot;requestMapping\&quot;:{\&quot;04attachDocumentRq:attachDocInput:documentDtl:validFromDt\&quot;:\&quot;[\\\&quot;ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls:DocumentData:documentDtl:validFromDt116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;04attachDocumentRq:attachDocInput:documentDtl:documentCreateDt\&quot;:\&quot;[\\\&quot;docCreateDate116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;03attachDocumentRq:attachDocInput:documentDtl:documentRef\&quot;:\&quot;[\\\&quot;ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls:DocumentData:documentDtl:documentRef116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;03attachDocumentRq:attachDocInput:documentDtl:documentCategory\&quot;:\&quot;[\\\&quot;ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls:DocumentData:documentDtl:documentCategory116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;03attachDocumentRq:attachDocInput:documentDtl:documentDesc\&quot;:\&quot;[\\\&quot;_HiddenVector_ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls116a34bb033224cR%8822\\\&quot;,\\\&quot;03DocumentData_documentDtl_documentDesc\\\&quot;]\&quot;,\&quot;03attachDocumentRq:attachDocInput:documentDtl:documentType\&quot;:\&quot;[\\\&quot;ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls:DocumentData:documentDtl:documentType116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;03attachDocumentRq:attachDocInput:documentDtl:documentID\&quot;:\&quot;[\\\&quot;ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls:DocumentData:documentDtl:documentID116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;03dsxDatesAmended\&quot;:\&quot;[\\\&quot;dsxDatesAmended116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;03attachDocumentRq:attachDocInput:documentKeys:partyId\&quot;:\&quot;[\\\&quot;PartyID116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;03attachDocumentRq:attachDocInput:documentKeys:documentID\&quot;:\&quot;[\\\&quot;ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls:DocumentData:imageID116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;03attachDocumentRq:attachDocInput:documentDtl:issuingAuthority\&quot;:\&quot;[\\\&quot;ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls:DocumentData:documentDtl:issuingAuthority116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;03attachDocumentRq:attachDocInput:documentDtl:countryOfIssue\&quot;:\&quot;[\\\&quot;ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls:DocumentData:documentDtl:countryOfIssue116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;03attachDocumentRq:attachDocInput:documentDtl:partyID\&quot;:\&quot;[\\\&quot;PartyID116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;03attachDocumentRq:attachDocInput:documentDtl:docFaceRef\&quot;:\&quot;[\\\&quot;_HiddenVector_ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls116a34bb033224cR%8822\\\&quot;,\\\&quot;03DocumentData_documentDtl_docFaceRef\\\&quot;]\&quot;,\&quot;04attachDocumentRq:attachDocInput:documentDtl:validToDt\&quot;:\&quot;[\\\&quot;ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls:DocumentData:documentDtl:validToDt116a34bb033224cR%8822\\\&quot;]\&quot;,\&quot;09attachDocumentRq:attachDocInput:documentDtl:docVerified\&quot;:\&quot;[\\\&quot;_HiddenVector_ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls116a34bb033224cR%8822\\\&quot;,\\\&quot;09DocumentData_documentDtl_docVerified\\\&quot;]\&quot;},\&quot;responseMapping\&quot;:{\&quot;attachDocumentRs:attachDocOutput:documentKeys:documentID\&quot;:\&quot;{\\\&quot;ListDocuments:SearchPartyDocumentDataOutput:DocumentDataDtls:DocumentData:imageID116a34bb033224cR%8822\\\&quot;:\\\&quot;\\\&quot;}\&quot;},\&quot;serviceDisplayName\&quot;:\&quot;Scan Document 1\&quot;,\&quot;controlId\&quot;:\&quot;Attach_4116a34bb033224cR%8822\&quot;,\&quot;serviceName\&quot;:\&quot;CB_DOC_ScanDocument_PRC\&quot;}&quot;]});});</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Attach_4116a34bb033224cR%8822&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Attach_4116a34bb033224cR%8822']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='116a34bb033224cR%8822']/table/tbody/tr[17]/td[11]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image ID'])[1]/following::input[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Verified'])[2]/following::input[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOSTEXTENSION'])[1]/preceding::input[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COUNTRYCODE'])[1]/preceding::input[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[11]/input</value>
   </webElementXpaths>
</WebElementEntity>
